#azure_logic_app_endpoint: 'https://prod-04.centralus.logic.azure.com:443/workflows/********'
#baseURL: 'http://advancedapi.octoparse.com/'
#octoparse_username: '****'
#octoparse_password: '****'
#azure_storage_account_name: '****'
#azure_container_name: '****'
  # azure_container_name: '****'
#azure_storage_account_connection_string: 'DefaultEndpointsProtocol=https;AccountName=***;AccountKey=***;EndpointSuffix=***'
#prodExtracts: '***'
xyz_data_server: '****'
transaction_database: '****'
staging_database: '****'
azure_xyz_username: '****'
azure_xyz_password: '****'
production_database: '****'
