#azure_logic_app_endpoint: 'https://prod-04.centralus.logic.azure.com:443/workflows/2239b377ec954a4dbca2f52329a5524c/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BQMAYnHI3O8HnaO2I2jlrgLvY4NT1LjvHDDdvRAtffs'
#baseURL: 'http://advancedapi.octoparse.com/'
#octoparse_username: 'sbarber'
#octoparse_password: 'D3vfinity2021!'
#azure_storage_account_name: 'OasisData'
#azure_container_name: 'oasislive/'
  # azure_container_name: 'testcontainer/'
#azure_storage_account_connection_string: 'DefaultEndpointsProtocol=https;AccountName=oasisfileshare;AccountKey=LRuM97DzjuadLsBbAvrqTbdjNJwgt+nQU7Lj2Ry0sYnpBYOBZqVMewzM+21ye2Xtw2/wVEzfYH6SYkJBQdp20A==;EndpointSuffix=core.windows.net'
#prodExtracts: '472993'
oasis_data_server: 'oasis-data.database.windows.net'
transaction_database: 'OasisTransaction'
staging_database: 'OasisStaging'
azure_oasis_username: 'OasisWeb'
azure_oasis_password: 'Oa$i$W3b'
production_database: 'OasisProd'